#!/bin/bash

mkdir ./temp || true
cd ./temp
rm -Rf fflib-apex-mocks/
rm -Rf fflib-apex-common/
git clone https://github.com/apex-enterprise-patterns/fflib-apex-mocks.git
git clone https://github.com/apex-enterprise-patterns/fflib-apex-common.git

sfdx force:source:deploy -p ./fflib-apex-mocks/sfdx-source
sfdx force:source:deploy -p ./fflib-apex-common/sfdx-source