#!/bin/bash

mkdir ./temp || true
cd ./temp
rm -Rf fflib-apex-mocks/
rm -Rf fflib-apex-common/
git clone https://github.com/apex-enterprise-patterns/fflib-apex-mocks.git
git clone https://github.com/apex-enterprise-patterns/fflib-apex-common.git

sfdx project deploy start -c --source-dir ./fflib-apex-mocks/sfdx-source
sfdx project deploy start -c --source-dir ./fflib-apex-common/sfdx-source